name: EnchantmentAPI
main: com.rit.sucy.EnchantmentAPI
version: 4.28
depend:
  - PumpkinFramework
commands:
  enchantapi:
    description: root command
    usage: /enchantapi show the help menu
  enchantapi list:
    description: lists all registered custom enchantments
    usage: /enchantapi
    permission: EnchantmentAPI.list
    permission-message: You lack the privileges to use that!
  enchantapi add:
    description: applies a custom enchantment
    usage: /enchantapi add <enchantName> [enchantLevel]
    permission: EnchantmentAPI.admin
    permission-message: You lack the privileges to use that!
  enchantapi reload:
    description: reloads the enchantments
    usage: /enchantapi reload
    permission: EnchantmentAPI.admin
    permission-message: You lack the privileges to use that!
  enchantapi book:
    description: creates a book with enchantment details
    usage: /enchantapi book
    permission: EnchantmentAPI.book
    permission-message: You lack the privileges to use that!
permissions:
  EnchantmentAPI.list:
    description: basic list of enchantments
    default: true
  EnchantmentAPI.book:
    description: gives a book with enchantment descriptions
    default: true
  EnchantmentAPI.admin:
    description: applying enchantments
    default: op
  EnchantmentAPI.table:
    description: getting custom enchantments from the table
    default: true
  EnchantmentAPI.names:
    description: getting random names on enchant
    default: true
  EnchantmentAPI.enchant:
    description: access to all enchantments
    default: true
  EnchantmentAPI.enchant.vanilla:
    description: access to all vanilla enchantments
    default: true