name: PumpkinEconomy
version: '${version}'
main: me.fakepumpkin7.pumpkineconomy.PumpkinEconomy
api-version: '1.8.9'
commands:
  balance:
    usage: /balance <player>
    aliases:
      - bal
  pay:
    usage: /pay <player> <amount>
  withdraw:
    usage: /withdraw <amount>

