name: PumpkinEnchants
version: '${version}'
main: me.fakepumpkin7.pumpkinenchants.PumpkinEnchants
depend:
  - PumpkinFramework
  - EnchantmentAPI
commands:
  enchitem:
    usage: /enchitem <enchant> <level>
  enchants:
    usage: /enchants
    aliases:
      - enchant
      - enchantments
      - enchantment
      - rune
      - runes